import type { Metadata } from 'next'
import './pdp.css'
import { notFound } from 'next/navigation'
import { getStoreData, getProductBySlug, getRelatedProducts } from '@/lib/storeData'
import { buildOffersList, offersListToJsonLdValue } from '@/lib/jsonLdOffers'
import { pdpFetchLimiter } from '@/lib/concurrencyLimit'
import { getSiteSettings, isEnabled } from '@/lib/getSiteSettings'
import { supabase as anonClient } from '@/lib/supabase'
import { savingsPercent, parseJsonArray, truncate } from '@/lib/utils'
import { sanitizeHtml } from '@/lib/server/sanitize'
import type { Product, ProductVariant, SiteSettings } from '@/types'
import ProductGallery from '@/components/product/ProductGallery'
import AddToCartSection from '@/components/product/AddToCartSection'
import CertificateCard from '@/components/product/CertificateCard'
import ReviewsSection from '@/components/product/ReviewsSection'
import RelatedProducts from '@/components/product/RelatedProducts'
import PincodeRow from '@/components/product/PincodeRow'
import Breadcrumb from '@/components/ui/Breadcrumb'
import Link from 'next/link'
import Image from 'next/image'

export const revalidate = 3600

// BUG FIX (Next.js 15+/16 migration): `params` is now a Promise.
interface Props { params: Promise<{ slug: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params
  const { product } = await fetchProductData(slug)
  if (!product) return { title: 'Product Not Found' }

  const rawDesc = product.ai_description || product.short_description || `Buy ${product.name} online — pure Himalayan.`
  // BUG FIX (3.1 + 5.3): use product.name only so the layout template
  // appends " | HimVeda by Pahadi Roots" exactly once.
  // BUG FIX (5.3): use the existing truncate() utility (word-boundary aware,
  // adds ellipsis) instead of the raw .slice(0,155) that cut mid-word.
  const desc = truncate(rawDesc.replace(/<[^>]+>/g, ''), 155)
  const canonicalUrl = `https://www.pahadiroots.com/products/${product.slug}`
  // BUG FIX: fell back to `[]` (no image at all) when a product has no
  // image_url — same class of bug as page.tsx/blog/collections, causing a
  // broken WhatsApp/Facebook share preview for any product without a photo.
  // Falls back to the real logo instead.
  const ogImage = [{ url: product.image_url || '/logo.png', width: 800, height: 800, alt: product.name }]

  return {
    // BUG FIX (3.1): was `${product.name} — HimVeda by Pahadi Roots` which rendered
    // "Lakadong Turmeric — HimVeda by Pahadi Roots | HimVeda by Pahadi Roots" (brand name twice)
    title: product.name,
    description: desc,
    // BUG FIX (5.1): add canonical so the slug URL is always authoritative
    alternates: { canonical: canonicalUrl },
    openGraph: {
      title: `${product.name} | HimVeda by Pahadi Roots`,
      description: desc,
      // BUG FIX (3.2): og:url was missing — Meta uses it as the share-cache
      // de-dup key, so every product shared the homepage card
      url: canonicalUrl,
      images: ogImage,
    },
    // BUG FIX (3.2): twitter was never overridden so all product pages
    // inherited the layout's generic hardcoded Twitter card
    twitter: {
      card:        'summary_large_image',
      title:       `${product.name} | HimVeda by Pahadi Roots`,
      description: desc,
      images:      ogImage.map(i => i.url),
    },
  }
}

export default async function ProductPage({ params }: Props) {
  const { slug } = await params
  const [{ product, variants, images, stateData, categoryName, related, reviewStats, reviews, certificate }, siteSettings] = await Promise.all([
    fetchProductData(slug),
    getSiteSettings(),
  ])

  if (!product) notFound()

  // NEW — Honey PDP detection (brand redesign). Was a bare string equality
  // against 'himalayan-wild-honey', which broke silently the moment the
  // product's slug changed case or was regenerated by a rename (e.g. to
  // something like 'himalayan-wild-manali-honey') — the exact bug Mishika
  // hit. Normalized to lower-case + trimmed, and covers both the original
  // and the likely-renamed slug so a rename doesn't silently disable every
  // new section again. FLAG: this is still slug-string matching, which is
  // inherently fragile to a future rename — the durable fix is a real
  // per-product flag/column (e.g. has_premium_pdp) instead of matching
  // text. Please confirm the exact current slug (check the browser address
  // bar on the product page) so this can be pinned precisely.
  const HONEY_PDP_SLUGS = ['himalayan-wild-honey', 'himalayan-wild-manali-honey']
  const isHoneyPdp = HONEY_PDP_SLUGS.includes((product.slug || '').toLowerCase().trim())

  const settings: SiteSettings = siteSettings as SiteSettings

  const freeShipMin    = parseInt(settings.free_shipping_min || '0')
  const flatShipCharge = parseInt(settings.flat_shipping_charge || '0')
  const showReviews     = isEnabled(settings.show_reviews_on_pdp)
  const showRelated     = isEnabled(settings.show_related_products)
  const showCertificate = isEnabled(settings.show_certificates)

  // Images: product_images table (full res, sorted) → fallback image_url
  // SEO/A11y FIX: every gallery photo previously got the exact same alt
  // text (just product.name) — product_images has no per-image caption
  // column to draw real distinguishing text from, and inventing fake
  // captions ("front view", "close-up") would be misleading since we don't
  // actually know what each photo shows. Appending position ("image 2 of
  // 4") is the honest middle ground: screen reader users navigating the
  // gallery can tell photos apart, and it's still accurate. First image
  // stays unnumbered since it's the one used everywhere else (cards, OG,
  // JSON-LD) with plain product.name.
  const allImages = images.length > 0
    ? images.map((i: any, idx: number) => ({
        url: i.image_url || i.url,
        alt: images.length > 1 ? `${product.name} — image ${idx + 1} of ${images.length}` : product.name,
      }))
    : product.image_url ? [{ url: product.image_url, alt: product.name }] : []

  // Active variants sorted by price
  const activeVariants: ProductVariant[] = variants
    .filter((v: any) => v.is_active)
    .sort((a: any, b: any) => a.price - b.price)
    .map((v: any) => ({ ...v, size: v.variant_value ?? v.size ?? v.variant_label ?? '' }))

  const baseVariant = activeVariants.length > 0
    ? activeVariants.reduce((min: any, v: any) => v.price < min.price ? v : min, activeVariants[0])
    : null

  // BUG FIX (catalogue-wide audit, Aug 2026): products.price is a legacy
  // column the pricing engine no longer writes to — prefer selling_price.
  const displayPrice = baseVariant?.price ?? product.selling_price ?? product.price
  const displayMRP   = baseVariant?.mrp ?? product.mrp ?? product.selling_price ?? product.price
  const savings      = savingsPercent(displayMRP ?? displayPrice, displayPrice)
  // BUG FIX (MEDIUM – null stockCount): product.available_stock can be null from
  // the DB. `null > 0` = false (shows OOS correctly) but `null <= 5` = false too
  // (silently skips the "Only X left" branch). Coerce to a number so all
  // comparisons behave as expected: null → 0 (treated as out of stock).
  const stockCount   = Number(baseVariant?.available_stock ?? product.available_stock ?? 0)
  const inStock      = stockCount > 0

  // AI content
  const benefits    = parseJsonArray(product.ai_health_benefits)
  const howToUse    = parseJsonArray(product.ai_how_to_use)
  const storageTips = parseJsonArray(product.ai_storage_tips)

  // Region
  const regionName  = stateData?.name || 'Himalayan Region'
  const stateImg    = stateData?.image_path || stateData?.image_url || ''
  const rEmoji      = ({ 'Assam': '🌿', 'Himachal Pradesh': '🏔️', 'Uttarakhand': '🌲',
    'Jammu & Kashmir': '❄️', 'Sikkim': '🌸', 'Nagaland': '🌿',
    'Meghalaya': '☁️', 'Ladakh': '⛰️' } as Record<string, string>)[regionName] || '🏔️'

  // Description: 4-layer fallback matching old site
  // BUG FIX (02): sanitize HTML from DB/AI pipeline before dangerouslySetInnerHTML
  const descHtml = sanitizeHtml(
    (product.ai_description?.trim())
    || (product.long_description?.trim())
    || (product.short_description ? `<p>${product.short_description}</p>` : '')
    || '<p>Authentic Himalayan product sourced directly from local farmers. No preservatives, no additives — pure and natural.</p>'
  )

  // BUG FIX (02): sanitize ai_who_should_buy before dangerouslySetInnerHTML
  const whoHtml = product.ai_who_should_buy ? sanitizeHtml(product.ai_who_should_buy) : ''

  // BUG FIX (3.8): highlights were computed from product.tags but never
  // rendered, and the JSON.parse had no try/catch. Removed entirely.

  // WhatsApp
  const waNumber = (settings.whatsapp_number || '919899984895').replace(/\D/g, '')
  const waNumDisplay = waNumber.replace('91', '').replace(/(\d{5})(\d{5})/, '$1 $2')

  // BUG FIX (3.3): aggregateRating was hardcoded to 4.8 / 39 on every product.
  // Now wired to real review data from fetchProductData.
  // JSON-LD: only include aggregateRating when there are real reviews.
  // SEO FIX: aggregateRating alone was wired in, but individual Review
  // objects (with the actual reviewer/text/date) weren't — Google's
  // Product rich-result docs list both as valid, and having real Review
  // entries strengthens rich-result eligibility beyond just the aggregate
  // number. Capped at 5 most recent (matches what ReviewsSection shows
  // above the fold) so this doesn't bloat the page with dozens of reviews'
  // full text in every response. No effect today (reviews is empty in
  // production) — this activates automatically as real reviews come in,
  // no further code change needed.
  const reviewsForJsonLd = (reviews || []).slice(0, 5).map((r: any) => ({
    '@type': 'Review',
    reviewRating: { '@type': 'Rating', ratingValue: String(r.rating) },
    author: { '@type': 'Person', name: r.customer_name || 'Verified Buyer' },
    ...(r.created_at ? { datePublished: new Date(r.created_at).toISOString().slice(0, 10) } : {}),
    ...(r.review_text ? { reviewBody: r.review_text } : {}),
  }))

  // BUG FIX (MEDIUM – audit finding #5, single-Offer JSON-LD): see
  // lib/jsonLdOffers.ts for the full rationale (AggregateOffer is explicitly
  // not the right schema.org tool for size/variant pricing per Google's docs;
  // per-variant Offer array with sku is the documented approach).
  const offersList = buildOffersList(
    { name: product.name, slug: product.slug, sku: product.sku },
    activeVariants.map((v: any) => ({ size: v.size, price: v.price, available_stock: v.available_stock, sku: v.sku })),
    displayPrice,
    inStock,
    settings.site_name,
  )

  const jsonLd: Record<string, unknown> = {
    '@context': 'https://schema.org/',
    '@type':    'Product',
    name:        product.name,
    description: (product.short_description || ''),
    image:       allImages.map((i: any) => i.url),
    url:         `https://www.pahadiroots.com/products/${product.slug}`,
    brand:       { '@type': 'Brand', name: settings.site_name || 'HimVeda by Pahadi Roots' },
    // SEO FIX: Product structured data had no `category` — Google's Product
    // docs list it as a recommended field (helps Search/Shopping categorize
    // the item correctly) and it costs nothing extra to fetch since it's a
    // single indexed lookup by the category_id every product already has.
    ...(categoryName ? { category: categoryName } : {}),
    ...(reviewStats && reviewStats.count > 0 ? {
      aggregateRating: {
        '@type':      'AggregateRating',
        ratingValue:  reviewStats.avg.toFixed(1),
        reviewCount:  String(reviewStats.count),
      },
    } : {}),
    ...(reviewsForJsonLd.length > 0 ? { review: reviewsForJsonLd } : {}),
    ...(offersListToJsonLdValue(offersList) !== undefined
      ? { offers: offersListToJsonLdValue(offersList) }
      : {}),
  }

  const crumbs = [
    { label: 'Home', href: '/' },
    { label: 'All Products', href: '/products' },
    { label: product.name },
  ]

  return (
    <>
      {/* BUG FIX (HIGH – JSON-LD XSS): JSON.stringify does NOT escape < / > / &,
          so a product name containing </script> would break out of the JSON-LD block
          (stored XSS). We replace the three characters that end/escape HTML contexts
          with their Unicode escape sequences, which are valid JSON and safe in a
          <script> tag per the HTML5 spec. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(jsonLd)
            .replace(/</g, '\\u003c')
            .replace(/>/g, '\\u003e')
            .replace(/&/g, '\\u0026'),
        }}
      />
      {/* BUG FIX (MEDIUM – missing BreadcrumbList JSON-LD): the visual breadcrumb
          was correct but Google had no structured data to parse for sitelinks in
          SERPs. BreadcrumbList is a separate ld+json block — it doesn't merge with
          the Product block above. Each crumb needs a position (1-indexed) and an
          item URL; the last crumb (current page) has no URL per schema.org spec. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'BreadcrumbList',
            itemListElement: [
              {
                '@type': 'ListItem',
                position: 1,
                name: 'Home',
                item: 'https://www.pahadiroots.com/',
              },
              {
                '@type': 'ListItem',
                position: 2,
                name: 'All Products',
                item: 'https://www.pahadiroots.com/products',
              },
              {
                '@type': 'ListItem',
                position: 3,
                name: product.name,
                // Current page — item URL omitted per schema.org BreadcrumbList spec
              },
            ],
          })
            .replace(/</g, '\\u003c')
            .replace(/>/g, '\\u003e')
            .replace(/&/g, '\\u0026'),
        }}
      />

      {/* ── Breadcrumb + Back pill in one compact row ── */}
      <div className="pdp-nav-row">
        <Breadcrumb crumbs={crumbs} className="pdp-breadcrumb" />
        <Link href="/products" className="pdp-back-pill">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
            <polyline points="15,18 9,12 15,6" />
          </svg>
          All Products
        </Link>
      </div>

      <div className="pdp-page-bg">

        {/* ── Main two-column layout ── */}
        <div className="pdp-wrap">

          {/* LEFT: Gallery */}
          <div className="pdp-img-col">
            <ProductGallery images={allImages} productName={product.name} savings={savings} />

            {/* NEW — Stat trio + Certificate, moved here below the gallery
                images per Mishika's marked location (Sept 2026). Stat trio
                is honey-specific (gated); Certificate is generic/shared and
                shown for any product with an active certificate linked. */}
            {isHoneyPdp && (
              <div className="pdp-stat-trio">
                <div><div className="pdp-stat-num">2</div><div className="pdp-stat-label">Himalayan Origins</div></div>
                <div><div className="pdp-stat-num">100%</div><div className="pdp-stat-label">Raw &amp; Unfiltered</div></div>
                <div><div className="pdp-stat-num">0</div><div className="pdp-stat-label">Additives</div></div>
              </div>
            )}
            {showCertificate && certificate && <CertificateCard certificate={certificate} />}
          </div>

          {/* RIGHT: Info */}
          <div className="pdp-info-col">

            {/* Region — vendor sub-line removed (BUG FIX: duplicated the
                brand identity already shown everywhere else on the page —
                header logo, footer, product schema — and hardcoded the old
                "5 Pahadi Roots" name instead of the current
                "HimVeda by Pahadi Roots" brand, so it was both redundant
                and stale). */}
            <div className="pdp-vendor">{rEmoji} {regionName}</div>

            {/* Title */}
            <h1 className="pdp-title">{product.name}</h1>

            {/* Short description / tagline */}
            {product.short_description && (
              <p className="pdp-tagline">{product.short_description}</p>
            )}

            {/* BUG FIX (3.3 + 3.6): Rating row — no longer hardcoded to 4.8/39.
                Only shown when real review data exists (reviewStats from DB).
                The "(N reviews)" span now scrolls to the reviews section on
                click instead of faking interactivity with no handler. */}
            {reviewStats && reviewStats.count > 0 && (
              <div className="pdp-rating-row">
                {/* BUG FIX (MEDIUM – stars always filled): previously rendered 5
                    identical filled SVG stars regardless of reviewStats.avg. A product
                    with 2.8 avg showed full stars, creating a UX + JSON-LD trust
                    mismatch. Now each star is individually filled/half/empty based on
                    the actual average using a per-star SVG clipPath gradient. */}
                <div className="pdp-stars" aria-label={`${reviewStats.avg.toFixed(1)} out of 5 stars`} role="img">
                  {[1,2,3,4,5].map(i => {
                    const fill = Math.min(1, Math.max(0, reviewStats!.avg - (i - 1)))
                    const pct  = Math.round(fill * 100)
                    const uid  = `star-fill-${i}`
                    return (
                      <svg key={i} className="pdp-star" viewBox="0 0 24 24" aria-hidden="true">
                        <defs>
                          <linearGradient id={uid} x1="0" x2="1" y1="0" y2="0">
                            <stop offset={`${pct}%`} stopColor="currentColor" />
                            <stop offset={`${pct}%`} stopColor="transparent" />
                          </linearGradient>
                        </defs>
                        <path
                          d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"
                          fill={`url(#${uid})`}
                          stroke="currentColor"
                          strokeWidth="1"
                        />
                      </svg>
                    )
                  })}
                </div>
                <span className="pdp-rating-num">{reviewStats.avg.toFixed(1)}</span>
                {/* BUG FIX (3.6): was styled as link but had no href/onClick */}
                <a href="#reviews" className="pdp-rating-count">({reviewStats.count} reviews)</a>
              </div>
            )}

            {/* Price block */}
            <div className="pdp-price-block">
              <div className="pdp-price-row">
                <span className="pdp-price">₹{displayPrice}</span>
                {displayMRP && displayMRP > displayPrice && (
                  <>
                    <span className="pdp-mrp">₹{displayMRP}</span>
                    <span className="pdp-save-badge">SAVE {savings}%</span>
                  </>
                )}
              </div>
              <p className="pdp-tax-note">
                MRP inclusive of all taxes{activeVariants.length > 0 && baseVariant ? ` · ${baseVariant.size}` : ''}
              </p>
              {/* BUG FIX (3.4): urgency bar was always capped at 95% because
                  (100 - x) * 2 >= 95 for any x <= 52, and the bar only renders
                  when stockCount < 50. Now uses initial_stock when available for
                  a real sold-percentage; falls back to a proportional formula. */}
              {stockCount > 0 && stockCount < 50 && (
                <div className="pdp-urgency">
                  <div className="pdp-urgency-label">🔥 Only {stockCount} left — selling fast!</div>
                  <div className="pdp-urgency-track">
                    <div
                      className="pdp-urgency-fill"
                      style={{
                        width: (() => {
                          const initial = (product as any).initial_stock
                          if (initial && initial > 0) {
                            // Real sold-percentage based on initial stock
                            return `${Math.min(Math.round((1 - stockCount / initial) * 100), 95)}%`
                          }
                          // Fallback: proportional within the 1–49 visible range
                          // 1 unit → ~95%, 49 units → ~2%
                          return `${Math.round(((50 - stockCount) / 49) * 93 + 2)}%`
                        })(),
                      }}
                    />
                  </div>
                </div>
              )}
            </div>

            {/* Key Benefits card */}
            {benefits.length > 0 && (
              <div className="pdp-benefits-card">
                <div className="pdp-benefits-title">✨ Key Benefits</div>
                {benefits.map((b: any, i: number) => (
                  <div key={i} className="pdp-ben-item">
                    <div className="pdp-ben-icon">{typeof b === 'object' ? (b.icon || '✓') : '✓'}</div>
                    <div>
                      <div className="pdp-ben-title">{typeof b === 'object' ? b.title : b}</div>
                      {typeof b === 'object' && b.desc && (
                        <div className="pdp-ben-desc">{b.desc}</div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Variant + Qty + Buttons — Client Component */}
            <AddToCartSection product={product} variants={activeVariants} settings={settings} />

            {/* Stock indicator */}
            <div className="pdp-stock-row">
              <div className={`pdp-stock-dot${stockCount <= 0 ? ' oos' : stockCount <= 5 ? ' low' : ''}`} />
              <span>
                {stockCount <= 0 ? 'Out of Stock'
                  : stockCount <= 5 ? `Only ${stockCount} left!`
                  : stockCount <= 20 ? `${stockCount} in stock`
                  : 'In Stock'}
              </span>
            </div>

            {/* BUG FIX (3.5): PincodeRow is now a real client component with
                state, validation, and a WhatsApp-based delivery-check handler.
                waNumber is actually used. */}
            <PincodeRow waNumber={waNumber} />

            {/* Share row */}
            <ShareRow
              productName={product.name}
              productSlug={product.slug}
              productImage={product.image_url}
              productPrice={displayPrice}
              facebookUrl={settings.social_facebook}
              instagramUrl={settings.social_instagram}
              youtubeUrl={settings.social_youtube}
            />

            {/* Delivery bar */}
            <div className="pdp-delivery-bar">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="1" y="3" width="15" height="13" /><polygon points="16,8 20,8 23,11 23,16 16,16" />
                <circle cx="5.5" cy="18.5" r="2.5" /><circle cx="18.5" cy="18.5" r="2.5" />
              </svg>
              {freeShipMin === 0
                ? '🚚 Free delivery on all orders · Pan India · Metro 3–5 days · Others 7–12 days'
                : `🚚 Pan India · Free above ₹${freeShipMin} (₹${flatShipCharge} below) · Metro 3–5 days · Others 7–12 days`}
            </div>

            {/* Certificate moved up near the top — see stat trio above */}

            {/* Origin card — gated off for honey: double-checked, this exact
                text is duplicated by Journey step 01 and Know Your Source
                below. Left fully intact for every other product. */}
            {!isHoneyPdp && (
              <div className="pdp-origin-card">
                <div className="pdp-origin-head">
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="rgba(255,255,255,.9)" strokeWidth="2" strokeLinejoin="round">
                    <polygon points="3 20 9 8 13 14 16 10 21 20" /><circle cx="18.5" cy="5.5" r="1.5" fill="#f0c840" stroke="none" />
                  </svg>
                  Himalayan Origin Story
                </div>
                <div className="pdp-origin-body">
                  <div className="pdp-origin-map">
                    {stateImg
                      ? <Image src={stateImg} alt={regionName} width={80} height={80} style={{ width: '100%', height: '100%', objectFit: 'cover', borderRadius: '50%' }} />
                      : <span style={{ fontSize: '26px', lineHeight: '1' }}>{rEmoji}</span>}
                  </div>
                  <div className="pdp-origin-text">
                    <div className="pdp-origin-region">{regionName}</div>
                    <p>Sourced directly from farming families in {regionName}, nestled in the pristine Himalayas. Grown at altitude, harvested with traditional methods — pure as the mountains.</p>
                  </div>
                </div>
              </div>
            )}

          </div>
        </div>

        {/* NEW — Journey story section (additive, brand redesign).
            FLAG for Mishika: same as the stat trio above — this is honey-
            specific copy and photography, gated to this one product slug.
            Photos are the real ones you sent, saved to
            /public/journey/honey/. Rolling this out to other products
            means either writing a per-product version of this block or
            moving this content into an admin-editable field + a generic
            component that maps images/copy per product. */}
        {isHoneyPdp && (
          <div className="pdp-journey">
            <div className="pdp-journey-head">
              <div className="pdp-journey-eyebrow">The Journey</div>
              <h2 className="pdp-journey-title">From the Himalayas to Your Home</h2>
            </div>

            <div className="pdp-journey-row">
              <div className="pdp-journey-media">
                <Image src="/journey/honey/01-origin.png" alt="Beehives on a Himalayan hillside at sunrise" width={800} height={640} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
              </div>
              <div className="pdp-journey-text">
                <div className="pdp-journey-num">01 — Origin</div>
                <h3 className="pdp-journey-h3">Where it begins. <em>High above Manali.</em></h3>
                <p className="pdp-journey-p">Sourced directly from farming families in Himachal Pradesh — hives set on the forested slopes above Manali, grown at altitude and harvested with traditional methods.</p>
              </div>
            </div>

            <div className="pdp-journey-row rev">
              <div className="pdp-journey-media">
                <Image src="/journey/honey/02-landscape.png" alt="Bees foraging on wild Himalayan blossoms" width={800} height={640} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
              </div>
              <div className="pdp-journey-text">
                <div className="pdp-journey-num">02 — Landscape</div>
                <h3 className="pdp-journey-h3">The flowers behind it. <em>Wild, not planted.</em></h3>
                <p className="pdp-journey-p">Wildflowers, rhododendrons, and medicinal herbs growing at high altitude give this honey its distinct floral character.</p>
              </div>
            </div>

            <div className="pdp-journey-row">
              <div className="pdp-journey-media">
                <Image src="/journey/honey/03-harvest.png" alt="Beekeeper lifting a honeycomb frame" width={800} height={640} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
              </div>
              <div className="pdp-journey-text">
                <div className="pdp-journey-num">03 — Harvest</div>
                <h3 className="pdp-journey-h3">Lifted by hand. <em>Frame by frame.</em></h3>
                <p className="pdp-journey-p">Each frame is checked and lifted by hand at the hive, the way it has always been done here.</p>
              </div>
            </div>

            <div className="pdp-journey-row rev">
              <div className="pdp-journey-media">
                <Image src="/journey/honey/04-handling.png" alt="Honeycomb being strained into raw honey" width={800} height={640} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
              </div>
              <div className="pdp-journey-text">
                <div className="pdp-journey-num">04 — Handling</div>
                <h3 className="pdp-journey-h3">From comb to jar. <em>Nothing added.</em></h3>
                <p className="pdp-journey-p">Never heated, never filtered — just raw honey drained straight from the comb, preserving its natural enzymes and crystalline structure.</p>
              </div>
            </div>

            <div className="pdp-journey-row">
              <div className="pdp-journey-media placeholder">
                <div className="pdp-journey-placeholder-text">Every batch is lab tested before it ships</div>
              </div>
              <div className="pdp-journey-text">
                <div className="pdp-journey-num">05 — Testing</div>
                <h3 className="pdp-journey-h3">Checked before it travels. <em>Lab verified.</em></h3>
                <p className="pdp-journey-p">Tested for purity, heavy metals, pesticides, and active ingredients — the same certificate shown above, before any jar leaves for you.</p>
              </div>
            </div>

            <div className="pdp-journey-row rev">
              <div className="pdp-journey-media">
                <Image src="/journey/honey/06-bottling.png" alt="Himalayan Wild Honey jar, sealed and labelled" width={800} height={640} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
              </div>
              <div className="pdp-journey-text">
                <div className="pdp-journey-num">06 — Bottling</div>
                <h3 className="pdp-journey-h3">Sealed with care. <em>Glass, not plastic.</em></h3>
                <p className="pdp-journey-p">Packed in glass jars with recycled cardboard — zero single-use plastic, the same as every HimVeda product.</p>
              </div>
            </div>

            <div className="pdp-journey-row">
              <div className="pdp-journey-media">
                <Image src="/journey/honey/07-your-home.png" alt="Himalayan Wild Honey jar ready for your home" width={800} height={640} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
              </div>
              <div className="pdp-journey-text">
                <div className="pdp-journey-num">07 — Your Home</div>
                <h3 className="pdp-journey-h3">From the mountains. <em>To your table.</em></h3>
                <p className="pdp-journey-p">Dispatched within 1–2 business days, so the same jar that left the hive reaches your kitchen with nothing changed along the way.</p>
              </div>
            </div>
          </div>
        )}

        {/* NEW — Why It's Different (additive, brand redesign). Gated to
            honey. Claims used: Raw & Unfiltered / Lab Tested & Certified are
            the existing verified label + certificate data; High Altitude
            Origin and Small Batch are per Mishika's direct confirmation
            (Sept 2026) — no specific altitude figure or batch size is
            stated since neither is verified/available. */}
        {isHoneyPdp && (
          <div className="pdp-why-diff">
            <div className="pdp-journey-head">
              <div className="pdp-journey-eyebrow">Why It's Different</div>
            </div>
            <div className="pdp-why-diff-grid">
              <div className="pdp-why-diff-card">
                <div className="pdp-why-diff-icon">🍯</div>
                <div className="pdp-why-diff-title">Raw &amp; Unfiltered</div>
                <div className="pdp-why-diff-desc">Never heated or filtered — drained straight from the comb.</div>
              </div>
              <div className="pdp-why-diff-card">
                <div className="pdp-why-diff-icon">🏔️</div>
                <div className="pdp-why-diff-title">High Altitude Origin</div>
                <div className="pdp-why-diff-desc">Harvested from wild hives set high in the Himalayas, above Manali and Spiti.</div>
              </div>
              <div className="pdp-why-diff-card">
                <div className="pdp-why-diff-icon">🐝</div>
                <div className="pdp-why-diff-title">Small Batch</div>
                <div className="pdp-why-diff-desc">Small, seasonal harvests — not mass-produced.</div>
              </div>
              <div className="pdp-why-diff-card">
                <div className="pdp-why-diff-icon">✅</div>
                <div className="pdp-why-diff-title">Fully Certified</div>
                <div className="pdp-why-diff-desc">FSSAI licensed and lab tested for purity, heavy metals, pesticides &amp; active ingredients.</div>
              </div>
            </div>
          </div>
        )}

        {/* NEW — Know Your Source (additive, brand redesign). Reuses the
            same regionName/stateImg/rEmoji already fetched above for the
            Origin card — no new data source, no invented geography. */}
        {isHoneyPdp && (
          <div className="pdp-source">
            <div className="pdp-journey-head">
              <div className="pdp-journey-eyebrow">Know Your Source</div>
              <h2 className="pdp-journey-title">Know Where Your Food Comes From</h2>
            </div>
            <div className="pdp-source-card">
              <div className="pdp-source-img">
                {stateImg
                  ? <Image src={stateImg} alt={regionName} width={140} height={140} style={{ width: '100%', height: '100%', objectFit: 'cover', borderRadius: '50%' }} />
                  : <span style={{ fontSize: '48px' }}>{rEmoji}</span>}
              </div>
              <div>
                <div className="pdp-source-region">Manali &amp; Spiti, {regionName}</div>
                <p className="pdp-source-text">The exact origin behind this jar — {regionName}. See the Journey above for the full account.</p>
              </div>
            </div>
          </div>
        )}

        {/* ── Accordion section ── */}
        {!isHoneyPdp && (
        <div className="pdp-acc-section">
          <div className="pdp-acc-list">

            {!isHoneyPdp && (
              <AccItem title="Description" icon="desc" open>
                {/* BUG FIX (02): sanitized above with server-safe sanitizeHtml() */}
                <div dangerouslySetInnerHTML={{ __html: descHtml }} />
              </AccItem>
            )}

            {!isHoneyPdp && howToUse.length > 0 && (
              <AccItem title="How to Use" icon="how">
                <ul>
                  {howToUse.map((s: any, i: number) => (
                    <li key={i}>{typeof s === 'string' ? s : s?.step || JSON.stringify(s)}</li>
                  ))}
                </ul>
              </AccItem>
            )}

            {!isHoneyPdp && storageTips.length > 0 && (
              <AccItem title="Storage Tips" icon="storage">
                <ul>
                  {storageTips.map((s: any, i: number) => (
                    <li key={i}>{typeof s === 'string' ? s : JSON.stringify(s)}</li>
                  ))}
                </ul>
              </AccItem>
            )}

            {!isHoneyPdp && whoHtml && (
              <AccItem title="Who Should Buy" icon="who">
                {/* BUG FIX (02): sanitized above with server-safe sanitizeHtml() */}
                <div dangerouslySetInnerHTML={{ __html: whoHtml }} />
              </AccItem>
            )}

            {!isHoneyPdp && (
              <AccItem title="Certifications" icon="cert">
                <div className="pdp-cert-badges">
                  <div className="pdp-cert-badge">🔬 Lab Tested</div>
                  <div className="pdp-cert-badge">🌿 100% Natural</div>
                  <div className="pdp-cert-badge">🏛️ FSSAI Licensed</div>
                  <div className="pdp-cert-badge">✅ No Adulterants</div>
                </div>
              </AccItem>
            )}

            {!isHoneyPdp && (
              <AccItem title="Shipping" icon="ship">
                <strong>Pan India Shipping</strong><br /><br />
                {freeShipMin === 0
                  ? 'Free shipping on all orders · COD available. '
                  : `Free shipping above ₹${freeShipMin} · Flat ₹${flatShipCharge} below. COD available. `}
                Dispatched within <strong>1–2 business days</strong>.<br />
                Metro cities: <strong>3–5 days</strong> · Non-metro / remote: <strong>7–12 days</strong>.
              </AccItem>
            )}

            {!isHoneyPdp && (
              <AccItem title="Returns & Refunds" icon="returns">
                ✅ <strong>Eligible:</strong> Damaged, defective or wrong item — report within <strong>48 hours</strong> with photo/video.<br /><br />
                ❌ <strong>Not eligible:</strong> Opened/used edible products or items reported after 48 hours.<br /><br />
                WhatsApp +91 {waNumDisplay} with order number & photo. Refunds within <strong>7–10 business days</strong>.
              </AccItem>
            )}

          </div>
        </div>
        )}

        {/* NEW — How to Enjoy, visual redesign of the existing How to Use
            accordion content (additive, brand redesign). Reuses the same
            howToUse array already parsed above — no new copy invented.
            The original "How to Use" accordion item above is left in
            place untouched, per instruction not to remove anything
            without confirmation — flagging the duplication to Mishika. */}
        {isHoneyPdp && howToUse.length > 0 && (
          <div className="pdp-enjoy">
            <div className="pdp-journey-head">
              <div className="pdp-journey-eyebrow">How to Enjoy</div>
              <h2 className="pdp-journey-title">How to Enjoy Your Honey</h2>
            </div>
            <div className="pdp-enjoy-grid">
              {howToUse.map((s: any, i: number) => (
                <div key={i} className="pdp-enjoy-card">
                  <div className="pdp-enjoy-num">{String(i + 1).padStart(2, '0')}</div>
                  <div className="pdp-enjoy-text">{typeof s === 'string' ? s : s?.step || ''}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* NEW — Natural Variation education (additive, brand redesign).
            General true-for-raw-honey facts, not batch-specific claims —
            safe without any product-specific data. */}
        {isHoneyPdp && (
          <div className="pdp-variation">
            <div className="pdp-journey-head">
              <div className="pdp-journey-eyebrow">Natural Variation</div>
              <h2 className="pdp-journey-title">No Two Harvests Are Exactly Alike</h2>
              <p className="pdp-source-text" style={{ marginTop: '14px' }}>
                Because this honey is raw and unfiltered, small differences between jars are normal — not a flaw.
              </p>
            </div>
            <div className="pdp-why-diff-grid">
              <div className="pdp-why-diff-card"><div className="pdp-why-diff-title">Colour</div><div className="pdp-why-diff-desc">Can shift lighter or darker between harvests depending on the season's bloom.</div></div>
              <div className="pdp-why-diff-card"><div className="pdp-why-diff-title">Aroma &amp; Taste</div><div className="pdp-why-diff-desc">Floral character varies with whatever was blooming at harvest time.</div></div>
              <div className="pdp-why-diff-card"><div className="pdp-why-diff-title">Crystallisation</div><div className="pdp-why-diff-desc">Raw honey crystallises naturally over time — a sign of purity, not spoilage. Warm the jar gently in lukewarm water if you prefer it liquid.</div></div>
              <div className="pdp-why-diff-card"><div className="pdp-why-diff-title">Storage</div><div className="pdp-why-diff-desc">Keep it cool and dark in an airtight glass jar — avoid plastic and direct sunlight.</div></div>
            </div>
          </div>
        )}

        {/* NEW — FAQ (additive, brand redesign). Every answer below reuses
            verified copy already established elsewhere on this page
            (description, storage tips, shipping, certificate). Two
            questions from the spec are left as honest placeholders since
            the underlying data doesn't exist yet — see brand-redesign
            notes on batch traceability and shelf life. */}
        {isHoneyPdp && (
          <div className="pdp-acc-section" style={{ marginTop: '8px' }}>
            <div className="pdp-journey-head" style={{ marginBottom: '24px' }}>
              <div className="pdp-journey-eyebrow">FAQ</div>
            </div>
            <div className="pdp-acc-list">
              <AccItem title="Where is the honey sourced?" icon="who">
                Manali &amp; Spiti, Himachal Pradesh — see the Journey above for the full account.
              </AccItem>
              <AccItem title="Is it raw and unfiltered?" icon="desc">
                Yes, always — see Description above for details.
              </AccItem>
              <AccItem title="How long does it last?" icon="desc">
                [ADD VERIFIED SHELF LIFE]
              </AccItem>
              <AccItem title="Can I see the lab report?" icon="cert">
                {showCertificate && certificate
                  ? <>Yes — <a href={certificate.reportUrl} target="_blank" rel="noopener noreferrer">view the Authenticity Report here</a>.</>
                  : '[ADD VERIFIED SOURCE INFORMATION]'}
              </AccItem>
              <AccItem title="How can I verify my batch?" icon="cert">
                [ADD VERIFIED SOURCE INFORMATION] — batch-level traceability isn't available yet.
              </AccItem>

              <AccItem title="Shipping" icon="ship">
                <strong>Pan India Shipping</strong><br /><br />
                {freeShipMin === 0
                  ? 'Free shipping on all orders · COD available. '
                  : `Free shipping above ₹${freeShipMin} · Flat ₹${flatShipCharge} below. COD available. `}
                Dispatched within <strong>1–2 business days</strong>.<br />
                Metro cities: <strong>3–5 days</strong> · Non-metro / remote: <strong>7–12 days</strong>.
              </AccItem>

              <AccItem title="Returns & Refunds" icon="returns">
                ✅ <strong>Eligible:</strong> Damaged, defective or wrong item — report within <strong>48 hours</strong> with photo/video.<br /><br />
                ❌ <strong>Not eligible:</strong> Opened/used edible products or items reported after 48 hours.<br /><br />
                WhatsApp +91 {waNumDisplay} with order number & photo. Refunds within <strong>7–10 business days</strong>.
              </AccItem>
            </div>
          </div>
        )}

        {/* ── Reviews ── */}
        {showReviews && (
          <div id="reviews" className="pdp-reviews-wrap">
            {/* BUG FIX (MEDIUM – ReviewsSection client-side SWR): reviews are now
                pre-fetched server-side and passed as a prop. No SWR, no layout shift,
                reviews are in the initial SSR HTML. */}
            <ReviewsSection reviews={reviews} />
          </div>
        )}

        {/* ── Related ──
            BUG FIX (3.9): was calling RelatedProducts with categoryId/excludeId
            which caused it to independently re-fetch the full catalog (a second
            getStoreData() call) and filter by category_id only — ignoring the
            already-computed `related` array (which matched state OR category).
            Now passes the pre-fetched array directly. */}
        {showRelated && related.length > 0 && (
          <div className="pdp-related-wrap">
            <RelatedProducts products={related as unknown as Array<{ id: number | string; [key: string]: unknown }>} />
          </div>
        )}

        {/* ── Why HimVeda by Pahadi Roots ── */}
        <WhySection />

      </div>
    </>
  )
}

// ─── Sub-components (Server) ──────────────────────────────────────────────────

const ACC_ICONS: Record<string, React.ReactNode> = {
  desc:    <svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>,
  how:     <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>,
  storage: <svg viewBox="0 0 24 24"><path d="M21 8v13H3V8"/><rect x="1" y="3" width="22" height="5" rx="1"/><line x1="10" y1="12" x2="14" y2="12"/></svg>,
  who:     <svg viewBox="0 0 24 24"><path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87"/><path d="M16 3.13a4 4 0 010 7.75"/></svg>,
  cert:    <svg viewBox="0 0 24 24"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>,
  ship:    <svg viewBox="0 0 24 24"><rect x="1" y="3" width="15" height="13" rx="1"/><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></svg>,
  returns: <svg viewBox="0 0 24 24"><polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 102.13-9.36L1 10"/></svg>,
}

function AccItem({ title, icon, open = false, children }: {
  title: string; icon: string; open?: boolean; children: React.ReactNode
}) {
  return (
    <details className="pdp-acc-item" open={open}>
      <summary className="pdp-acc-head">
        <div className="pdp-acc-head-left">
          <div className="pdp-acc-icon">{ACC_ICONS[icon]}</div>
          <span className="pdp-acc-title">{title}</span>
        </div>
        <div className="pdp-acc-chevron">
          <svg viewBox="0 0 14 14"><polyline points="2,4 7,10 12,4"/></svg>
        </div>
      </summary>
      <div className="pdp-acc-body">{children}</div>
    </details>
  )
}

function ShareRow({ productName, productSlug, productImage, productPrice, facebookUrl, instagramUrl, youtubeUrl }: {
  productName: string; productSlug: string; productImage: string | null; productPrice: number
  facebookUrl?: string; instagramUrl?: string; youtubeUrl?: string
}) {
  const url = `https://www.pahadiroots.com/products/${productSlug}`
  const waText = encodeURIComponent(`🌿 Check out *${productName}* at ₹${productPrice} on HimVeda by Pahadi Roots!\n🏔️ Pure Himalayan, directly from mountain farmers.\n👉 ${url}`)
  // Facebook, Instagram and YouTube all now open the brand's own page/
  // profile (social_facebook/social_instagram/social_youtube from
  // getSiteSettings, same values the footer uses) instead of a share
  // dialog for this one product — Facebook's sharer.php intent was
  // technically working, but it dropped a visitor into a share composer
  // instead of the brand's actual page, which read as "broken" from the
  // click. Instagram/YouTube never had a share-intent option to begin
  // with, so they were already follow links.
  const fbUrl = facebookUrl  || 'https://www.facebook.com/HimVedaByPahadiRoots'
  const igUrl = instagramUrl || 'https://www.instagram.com/5pahadiroots/?hl=en'
  const ytUrl = youtubeUrl   || 'https://www.youtube.com/@pahadiroots'
  return (
    <div className="pdp-share-row">
      <span className="pdp-share-label">Share on</span>
      <div className="pdp-share-icons">
        <a href={`https://wa.me/?text=${waText}`} target="_blank" rel="noopener noreferrer" className="pdp-share-btn pdp-share-wa" title="WhatsApp">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="#25d366"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/><path d="M12.004 2.003A9.997 9.997 0 002.007 12c0 1.762.461 3.418 1.268 4.861L2.003 22l5.29-1.247A9.952 9.952 0 0012.004 22c5.523 0 9.997-4.477 9.997-9.998A9.997 9.997 0 0012.004 2.003z"/></svg>
        </a>
        <a href={fbUrl} target="_blank" rel="noopener noreferrer" className="pdp-share-btn pdp-share-fb" title="Facebook">
          <svg width="17" height="17" viewBox="0 0 24 24" fill="#1877f2"><path d="M24 12.073C24 5.405 18.627 0 12 0S0 5.405 0 12.073C0 18.1 4.388 23.094 10.125 24v-8.437H7.078v-3.49h3.047V9.41c0-3.025 1.791-4.697 4.533-4.697 1.312 0 2.686.236 2.686.236v2.97h-1.513c-1.491 0-1.956.93-1.956 1.883v2.271h3.328l-.532 3.49h-2.796V24C19.612 23.094 24 18.1 24 12.073z"/></svg>
        </a>
        <a href={`https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(productName + ' — HimVeda by Pahadi Roots')}`} target="_blank" rel="noopener noreferrer" className="pdp-share-btn pdp-share-tw" title="X / Twitter">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="#000"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.74l7.73-8.835L1.254 2.25H8.08l4.261 5.633 5.903-5.633zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>
        </a>
        <a href={`https://pinterest.com/pin/create/button/?url=${encodeURIComponent(url)}&media=${encodeURIComponent(productImage || '')}&description=${encodeURIComponent(productName + ' — HimVeda by Pahadi Roots')}`} target="_blank" rel="noopener noreferrer" className="pdp-share-btn pdp-share-pin" title="Pinterest">
          <svg width="17" height="17" viewBox="0 0 24 24" fill="#e60023"><path d="M12 0C5.373 0 0 5.373 0 12c0 5.084 3.163 9.426 7.627 11.174-.105-.949-.2-2.405.042-3.441.218-.937 1.407-5.965 1.407-5.965s-.359-.719-.359-1.782c0-1.668.967-2.914 2.171-2.914 1.023 0 1.518.769 1.518 1.69 0 1.029-.655 2.568-.994 3.995-.283 1.194.599 2.169 1.777 2.169 2.133 0 3.772-2.249 3.772-5.495 0-2.873-2.064-4.882-5.012-4.882-3.414 0-5.418 2.561-5.418 5.207 0 1.031.397 2.138.893 2.738a.36.36 0 01.083.345l-.333 1.36c-.053.22-.174.267-.402.161-1.499-.698-2.436-2.889-2.436-4.649 0-3.785 2.75-7.262 7.929-7.262 4.163 0 7.398 2.967 7.398 6.931 0 4.136-2.607 7.464-6.227 7.464-1.216 0-2.359-.632-2.75-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24 12 24c6.627 0 12-5.373 12-12S18.627 0 12 0z"/></svg>
        </a>
        <a href={igUrl} target="_blank" rel="noopener noreferrer" className="pdp-share-btn pdp-share-ig" title="Instagram">
          <svg width="17" height="17" viewBox="0 0 24 24" fill="#E1306C"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838a6.162 6.162 0 100 12.324 6.162 6.162 0 000-12.324zm0 10.162a4 4 0 110-8 4 4 0 010 8zm6.406-11.845a1.44 1.44 0 100 2.881 1.44 1.44 0 000-2.881z"/></svg>
        </a>
        <a href={ytUrl} target="_blank" rel="noopener noreferrer" className="pdp-share-btn pdp-share-yt" title="YouTube">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="#ff0000"><path d="M23.498 6.186a3.016 3.016 0 00-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 00.502 6.186 31.5 31.5 0 000 12a31.5 31.5 0 00.502 5.814 3.016 3.016 0 002.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 002.122-2.136A31.5 31.5 0 0024 12a31.5 31.5 0 00-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg>
        </a>
      </div>
    </div>
  )
}

function WhySection() {
  return (
    <section className="pdp-why-bg">
      <div className="pdp-why-inner">
        <div className="pdp-why-chip">Our Promise</div>
        <h2 className="pdp-why-title">Why HimVeda by Pahadi Roots</h2>
        <p className="pdp-why-sub">Four pillars that define everything we do — mountain to doorstep.</p>
      </div>
      <div className="pdp-why-grid">
        {/* PILLAR 1: Lab Tested */}
        <div className="pdp-why-pillar">
          <div className="pdp-why-num">01</div>
          <svg viewBox="0 0 148 148" xmlns="http://www.w3.org/2000/svg" style={{width:'110px',height:'110px',marginBottom:'10px'}}>
            <defs><radialGradient id="lt1" cx="45%" cy="35%" r="65%"><stop offset="0%" stopColor="#f0f8e8"/><stop offset="100%" stopColor="#4a9858"/></radialGradient></defs>
            <circle cx="74" cy="74" r="74" fill="url(#lt1)"/>
            <rect x="54" y="112" width="40" height="6" rx="3" fill="#1a4828"/>
            <rect x="68" y="90" width="12" height="24" rx="2" fill="#2a6840"/>
            <rect x="68" y="58" width="8" height="36" rx="2" fill="#2a6840"/>
            <rect x="68" y="56" width="30" height="8" rx="2" fill="#1a4828"/>
            <rect x="70" y="44" width="8" height="16" rx="3" fill="#3a7850"/>
            <circle cx="74" cy="42" r="6" fill="#1a4828"/>
            <circle cx="74" cy="42" r="3" fill="#88c8f8" opacity=".8"/>
            <rect x="40" y="86" width="28" height="8" rx="1" fill="#c8e8f8" opacity=".9"/>
            <circle cx="52" cy="90" r="4" fill="#50a840" opacity=".7"/>
            <circle cx="108" cy="44" r="18" fill="#f0c840" opacity=".95"/>
            <circle cx="108" cy="44" r="14" fill="white" opacity=".9"/>
            <polyline points="100,44 106,50 118,36" stroke="#1a4828" strokeWidth="3.5" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
            <rect x="88" y="66" width="40" height="12" rx="3" fill="#1a4828" opacity=".85"/>
            <text x="108" y="75" fontSize="7" fontWeight="700" fill="white" textAnchor="middle">CERTIFIED</text>
            <circle cx="28" cy="30" r="11" fill="#f0c840" opacity=".88"/>
            <text x="22" y="35" fontSize="9" fontWeight="700" fill="#7a6000">LAB</text>
          </svg>
          <div className="pdp-why-pt">Lab Tested Purity</div>
          <p className="pdp-why-pd">Every batch tested for heavy metals, pesticides &amp; adulterants. Certificate with every order.</p>
        </div>
        {/* PILLAR 2: Direct from Farmers */}
        <div className="pdp-why-pillar">
          <div className="pdp-why-num">02</div>
          <svg viewBox="0 0 148 148" xmlns="http://www.w3.org/2000/svg" style={{width:'110px',height:'110px',marginBottom:'10px'}}>
            <defs><radialGradient id="fd2" cx="45%" cy="35%" r="65%"><stop offset="0%" stopColor="#d8f0d8"/><stop offset="100%" stopColor="#4a9858"/></radialGradient></defs>
            <circle cx="74" cy="74" r="74" fill="url(#fd2)"/>
            <polygon points="0,90 24,52 50,72 74,42 98,68 124,48 148,80 148,148 0,148" fill="#2a6840" opacity=".4"/>
            <polygon points="0,106 20,72 46,88 74,58 102,84 128,66 148,96 148,148 0,148" fill="#1a4828"/>
            <circle cx="116" cy="26" r="13" fill="#f0c840" opacity=".9"/>
            <text x="108" y="30" fontSize="7" fontWeight="700" fill="#7a6000">FARM</text>
            <text x="108" y="39" fontSize="7" fill="#7a6000">→HOME</text>
          </svg>
          <div className="pdp-why-pt">Direct from Farmers</div>
          <p className="pdp-why-pd">Zero middlemen. 200+ farming families across 12 Himalayan states — fair wages, always.</p>
        </div>
        {/* PILLAR 3: Eco Packaging */}
        <div className="pdp-why-pillar">
          <div className="pdp-why-num">03</div>
          <svg viewBox="0 0 148 148" xmlns="http://www.w3.org/2000/svg" style={{width:'110px',height:'110px',marginBottom:'10px'}}>
            <defs><radialGradient id="ed3" cx="45%" cy="42%" r="65%"><stop offset="0%" stopColor="#c8e8f8"/><stop offset="100%" stopColor="#5890c0"/></radialGradient></defs>
            <circle cx="74" cy="74" r="74" fill="url(#ed3)"/>
            <circle cx="74" cy="80" r="46" fill="#2878b8" opacity=".7"/>
            <line x1="74" y1="34" x2="74" y2="18" stroke="#38b040" strokeWidth="3.5" strokeLinecap="round"/>
            <path d="M74,28 Q58,20 60,8 Q70,16 74,28Z" fill="#50c850"/>
            <path d="M74,24 Q90,16 88,4 Q78,12 74,24Z" fill="#60d860"/>
            <circle cx="116" cy="30" r="13" fill="#f0c840" opacity=".9"/>
            <text x="110" y="35" fontSize="9" fontWeight="700" fill="#7a6000">ECO</text>
          </svg>
          <div className="pdp-why-pt">Eco Packaging</div>
          <p className="pdp-why-pd">Glass jars, recycled cardboard, zero single-use plastic. Packaging as clean as our products.</p>
        </div>
        {/* PILLAR 4: Give-Back Program */}
        <div className="pdp-why-pillar">
          <div className="pdp-why-num">04</div>
          <svg viewBox="0 0 148 148" xmlns="http://www.w3.org/2000/svg" style={{width:'110px',height:'110px',marginBottom:'10px'}}>
            <defs><radialGradient id="gb3" cx="45%" cy="35%" r="65%"><stop offset="0%" stopColor="#c8e8f8"/><stop offset="100%" stopColor="#5888b8"/></radialGradient></defs>
            <circle cx="74" cy="74" r="74" fill="url(#gb3)"/>
            <polygon points="0,106 20,72 46,88 74,58 102,84 128,66 148,96 148,148 0,148" fill="#2a5838"/>
            <circle cx="30" cy="38" r="13" fill="#f0c840" opacity=".88"/>
            <text x="24" y="43" fontSize="10" fontWeight="700" fill="#7a6000">5%</text>
          </svg>
          <div className="pdp-why-pt">Give-Back Program</div>
          <p className="pdp-why-pd">5% of every order funds Himalayan forest restoration and village school programs.</p>
        </div>
      </div>
    </section>
  )
}

// ─── Data fetcher — targeted queries via storeData helpers (SERVICE KEY, bypasses RLS) ──
// BUG FIX (HIGH – catalog fetch doesn't scale, per audit finding #1): this used to call
// getStoreData() and linear-scan the entire active catalog (up to 500 products, every
// variant, every image, every coupon) just to find one product by slug — a full-table
// fetch to render a single PDP on every cache miss, plus a silent 500-row cutoff that
// could 404 real, active products. Now uses getProductBySlug() (direct indexed lookup)
// and getRelatedProducts() (targeted category/state query) instead.
async function fetchProductData(slug: string) {
  // BUG FIX (CRITICAL — regression found post-deploy via Vercel logs): see
  // lib/concurrencyLimit.ts for the full incident writeup. Every product page
  // now does its own targeted (uncached) Supabase queries instead of sharing
  // one cached full-catalog fetch, and Next.js builds all product pages in
  // parallel — without a cap, that's N products × ~6 simultaneous requests
  // hammering Supabase's connection pool at once, which cascaded into
  // timeouts on unrelated routes across the whole app. This limiter caps how
  // many products' data-fetch pipelines run at once; the rest queue.
  return pdpFetchLimiter.run(() => fetchProductDataInner(slug))
}

async function fetchProductDataInner(slug: string) {
  try {
    const { product: rawProduct, variants: rawVariants, images: rawImages } = await getProductBySlug(slug)
    if (!rawProduct) return { product: null, variants: [], images: [], stateData: null, categoryName: null, related: [], reviewStats: null, reviews: [] }

    // Normalize badges
    const badges: string[] = Array.isArray(rawProduct.badges) ? rawProduct.badges : []
    const product: Product = {
      ...rawProduct,
      badges_bestseller: badges.includes('bestseller'),
      badges_new:        badges.includes('new'),
      badges_organic:    badges.includes('organic'),
      // BUG FIX (verified live against production schema): the `products`
      // table has no `sku` column at all — only `sku_backup` (see the
      // "BUG FIX ATTEMPT REVERTED" comment in lib/storeData.ts, which hit
      // this exact gap from the other direction and left a warning not to
      // guess column names without checking live schema first). The
      // Product TS type's `sku` field was therefore always undefined via
      // `select('*')`, so every read of `product.sku` (jsonLdOffers' single-
      // offer fallback, the JSON-LD offer builder call below) silently
      // no-op'd. Currently harmless in production — all 13 active products
      // have at least one variant, so the variant-less fallback path never
      // actually runs — but it's real dead code presenting as working, and
      // will misbehave the moment a variant-less product is ever added.
      // sku_backup is the real column holding this data; aliasing it here
      // (matching this file's own existing pattern of aliasing renamed
      // columns, e.g. variant `mrp` ← `original_price` below) fixes it at
      // the one normalization point instead of at every call site.
      sku: (rawProduct as any).sku_backup ?? null,
    }

    const variants = rawVariants.map((v: any) => ({
      ...v,
      size: v.variant_value ?? v.size ?? v.variant_label ?? '',
      // BUG FIX (found via manual line-by-line audit, same root cause as the
      // cart-upsells/wishlist/blog/search mrp bug): product_variants has no
      // literal `mrp` column — the real column is `original_price`. Without
      // this mapping, baseVariant?.mrp on line ~99 below was ALWAYS
      // undefined, so displayMRP silently fell back to the PRODUCT-level
      // mrp for every single product page view, regardless of which size
      // variant was selected — meaning a product with different discount
      // percentages per size would show the wrong strikethrough price.
      mrp: v.original_price ?? v.mrp ?? v.price,
    }))

    // Product images already sorted by sort_order via getProductBySlug()
    const images = rawImages

    // State, related products, and reviews are all independent of each other —
    // fetch them concurrently instead of one round-trip at a time.
    // BUG FIX (3.3): fetch real review aggregate from Supabase.
    // BUG FIX (MEDIUM – duplicate Supabase client): reuses shared anon client.
    // BUG FIX (MEDIUM – ReviewsSection client-side SWR): previously ReviewsSection
    // fetched reviews client-side via SWR after hydration, causing a visible layout
    // shift (skeleton → content). Now we fetch the full review rows here in the
    // server data-fetcher so they are part of the initial SSR HTML. ReviewsSection
    // becomes a pure display component that accepts pre-fetched rows as props.
    const [stateData, categoryRow, related, reviewResult, certResult] = await Promise.all([
      // State data — direct lookup instead of scanning the full states list
      product.state_id
        ? anonClient.from('states').select('*').eq('id', product.state_id).maybeSingle()
            .then(({ data }) => data || null)
        : Promise.resolve(null),

      // SEO FIX: category name for Product JSON-LD's `category` field —
      // products only stores category_id (a bare FK, no name), so this is a
      // single indexed lookup, same targeted-fetch pattern as stateData
      // directly above rather than a full categories table scan.
      product.category_id
        ? anonClient.from('categories').select('name').eq('id', product.category_id).maybeSingle()
            .then(({ data }) => data?.name || null)
        : Promise.resolve(null),

      // Related: same state OR same category, exclude self, max 4 — fetched via a
      // targeted query (BUG FIX (3.9) preserved: images/variants attached here so
      // RelatedProducts doesn't need its own follow-up fetch).
      getRelatedProducts({
        productId:  product.id,
        categoryId: product.category_id ?? null,
        stateId:    product.state_id ?? null,
        limit:      4,
      }),

      // Wrapped so a reviews DB error never 404s the PDP.
      anonClient
        .from('reviews')
        .select('id, customer_name, location, rating, review_text, created_at')
        .eq('product_id', product.id)
        .eq('status', 'approved')
        .order('created_at', { ascending: false })
        .limit(10)
        .then(
          ({ data }) => ({ data, error: null as unknown }),
          (error) => ({ data: null, error }),
        ),

      // Certificate ("Lab Tested & Verified" card) — per Sudhir (Sept 2026):
      // certificates cover a harvest/source, not a single pack, so this is
      // an active-certificate lookup via the product_certificates junction,
      // not a batch/order-specific query. No harvest or batch data is
      // stored or shown — see CertificatesTab in pahadi-admin for why.
      // !inner forces the join so is_active/product_id filters actually
      // apply (a left join would ignore filters on the embedded table).
      // Wrapped the same way reviews are — a certificate lookup failure
      // must never 404 the whole PDP.
      anonClient
        .from('certificates')
        .select('report_url, has_purity, has_heavy_metals, has_pesticides, has_active_ingredients, product_certificates!inner(product_id)')
        .eq('is_active', true)
        .eq('product_certificates.product_id', product.id)
        .order('created_at', { ascending: false })
        .limit(1)
        .maybeSingle()
        .then(
          ({ data }) => ({ data, error: null as unknown }),
          (error) => ({ data: null, error }),
        ),
    ])

    let reviewStats: { avg: number; count: number } | null = null
    let reviews: import('@/types').Review[] = []
    if (reviewResult.error) {
      // Non-fatal — PDP renders fine without reviews
      console.warn('[fetchProductData] review fetch failed:', reviewResult.error)
    } else if (reviewResult.data && reviewResult.data.length > 0) {
      const reviewRows = reviewResult.data
      reviews = reviewRows as import('@/types').Review[]
      const sum = reviewRows.reduce((acc: number, r: any) => acc + (r.rating || 0), 0)
      reviewStats = {
        avg:   sum / reviewRows.length,
        count: reviewRows.length,
      }
    }

    let certificate: { reportUrl: string; hasPurity: boolean; hasHeavyMetals: boolean; hasPesticides: boolean; hasActiveIngredients: boolean } | null = null
    if (certResult.error) {
      // Non-fatal — PDP renders fine without the certificate card, same as reviews above.
      console.warn('[fetchProductData] certificate fetch failed:', certResult.error)
    } else if (certResult.data) {
      const c = certResult.data as any
      certificate = {
        reportUrl:            c.report_url,
        hasPurity:            Boolean(c.has_purity),
        hasHeavyMetals:       Boolean(c.has_heavy_metals),
        hasPesticides:        Boolean(c.has_pesticides),
        hasActiveIngredients: Boolean(c.has_active_ingredients),
      }
    }

    return { product, variants, images, stateData, categoryName: categoryRow, related, reviewStats, reviews, certificate }
  } catch (err) {
    console.error('[fetchProductData] error:', err)
    return { product: null, variants: [], images: [], stateData: null, categoryName: null, related: [], reviewStats: null, reviews: [], certificate: null }
  }
}

export async function generateStaticParams() {
  try {
    const storeData = await getStoreData()
    return storeData.products.map((p: any) => ({ slug: p.slug || String(p.id) }))
  } catch { return [] }
}
